name: Publish packages

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 12
            - run: yarn code:check
            - run: yarn build

    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/
            - run: npm ci
            - run: |
                  for LIBRARY in $(yarn nx affected:libs --base=$last_version --head=$current_version --plain | awk 'NR > 2 && $1 != "Done" { print $1 }')
                  do
                    cd ./build/$LIBRARY
                    npm publish --registry https://npm.pkg.github.com --no-git-tag-version --no-push --yes
                    cd ..
                  done
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
