name: Publish packages

on:
    push:
        tags:
            - "v*"

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  cache: "yarn"

            - name: Setup Nx
              uses: nrwl/nx-set-shas@v2
              with:
                  main-branch-name: ${{ github.base_ref}}

            - name: Install NPM dependencies
              run: yarn install

            - name: Lint
              run: yarn lint

            - name: Test
              run: yarn test

            - name: Build
              run: yarn build && node tools/scripts/versions-matcher.js

            - name: Build storybook
              run: yarn storybook:build

            - name: Save artifact
              uses: actions/upload-artifact@master
              with:
                  name: build
                  path: build

            - name: Publish UI library
              uses: JS-DevTools/npm-publish@v1
              with:
                  package: build/ui/package.json
                  check-version: true
                  token: ${{ secrets.NPM_TOKEN }}

            - name: Publish UI library storybook
              uses: chromaui/action@v1
              with:
                  storybookBuildDir: build/storybooks/ui
                  token: ${{ secrets.GITHUB_TOKEN }}
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

            - name: Publish Utilities library
              uses: JS-DevTools/npm-publish@v1
              with:
                  package: build/utils/package.json
                  check-version: true
                  token: ${{ secrets.NPM_TOKEN }}

            - name: Notify
              uses: rtCamp/action-slack-notify@v2.2.0
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                  SLACK_USERNAME: honzachalupa/common
                  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
