name: Publish packages

on:
    push:
        branches: [develop, master]

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  cache: "yarn"
                  registry-url: "https://npm.pkg.github.com"

            - name: Setup Nx
              uses: nrwl/nx-set-shas@v2
              with:
                  main-branch-name: ${{ github.base_ref}}

            - name: Install NPM dependencies
              run: yarn install

            - name: Lint
              run: yarn lint

            - name: Test
              run: yarn test

            - name: Build
              run: yarn build

            - name: Publish UI library
              run: cd build/ui && npm publish && cd ../../
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish Utilities library
              run: cd build/utils && npm publish && cd ../../
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
