name: Publish packages

on:
    push:
        branches: [develop, master]

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  cache: "yarn"

            - name: Setup Nx
              uses: nrwl/nx-set-shas@v2
              with:
                  main-branch-name: ${{ github.base_ref}}

            - name: Install NPM dependencies
              run: yarn install

            - name: Lint
              run: yarn lint

            - name: Test
              run: yarn test

            - name: Build
              run: yarn build

            - name: Publish to NPM
              run: |
                  for LIBRARY in $(yarn nx affected:libs --base=$last_version --head=$current_version --plain | awk 'NR > 2 && $1 != "Done" { print $1 }')
                  do
                    cd ./build/$LIBRARY
                    npm publish --registry https://npm.pkg.github.com --no-git-tag-version --no-push --yes
                    cd ..
                  done
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
